[workspace]
members = [
    "cli",
    "relayer",
    "core/primitives",
    "chain/client",
    "chain/chain",
    "core/work",
    "core/signatory-set",
    "core/bitcoin",
    "worker",
    "scripts/make-checkpoint-header"
]

[profile.release]
overflow-checks = true

