[package]
name = "nomic-client"
version = "0.1.0"
authors = ["Judd <kepzorz@gmail.com>"]
edition = "2018"

[dependencies]
bitcoin = { version = "^0.19.1", features=["serde"]}
nomic-primitives = { path = "../../core/primitives" }
nomic-chain = { path = "../chain" }
bincode = "1.2.0"
serde_derive = "=1.0.98"
serde = { version = "=1.0.98", features=["derive"]}
tendermint = { git = "https://github.com/interchainio/tendermint-rs"}
serde_json = "1.0.41"

[dev-dependencies]
bitcoincore-rpc = "0.8.0-rc1"
