[package]
name = "nomic-chain"
version = "0.1.0"
authors = ["Judd <kepzorz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orga = { git = "https://github.com/nomic-io/orga" }
nomic-primitives = { path = "../../core/primitives" }
bitcoin = {version = "^0.19.1", features=["serde"] }
byteorder = "1.3.2"
serde = {version = "=1.0.98", features=["derive"] }
serde_derive = "=1.0.98"
bincode = "1.2.0"

