[package]
name = "nomic-chain"
version = "0.1.0"
authors = ["Judd <kepzorz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orga = { git = "https://github.com/nomic-io/orga" }
nomic-primitives = { path = "../../core/primitives" }
bitcoin = {version = "^0.19.1", features=["use-serde"] }
bitcoincore-rpc = "0.8.0-rc1"
byteorder = "1.3.2"
serde = {version = "=1.0.98", features=["derive"]  }
serde_derive = "=1.0.98"
bincode = "1.2.0"
serde_json = "1.0.41"
merk = "1.0.0-alpha.6"
abci2 = {git = "https://github.com/nomic-io/abci2"}
error-chain = "0.12.1"

