[package]
name = "nomic-primitives"
version = "0.1.0"
authors = ["Judd <kepzorz@gmail.com>"]
edition = "2018"

[dependencies]
nomic-bitcoin = { path = "../bitcoin" }
serde = { version= "1.0.104", features = ["derive"] }
failure = "0.1.7"
bincode = "1.2.1"
sha2 = "0.8.1"
orga = { git = "https://github.com/nomic-io/orga", rev = "ec61d9f63ebcc65e3012c943bbcf7eeb0351e4f6" }
secp256k1 = "0.17.2"
