[package]
name = "relayer"
version = "0.1.0"
authors = ["Judd <kepzorz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nomic-primitives = { path = "../core/primitives" }
bitcoincore-rpc = "0.7.0"

