[package]
name = "relayer"
version = "0.1.0"
authors = ["Judd <kepzorz@gmail.com>"]
edition = "2018"

[dependencies]
nomic-primitives = { path = "../core/primitives" }
nomic-client = { path = "../chain/client" }
bitcoincore-rpc = "0.7.0"
bitcoin = "0.21.0"

